/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Colores de marca extraídos del escudo del colegio San Juan.
        'brand-blue': '#264796',
        'brand-blue-dark': '#1b3670',
        'brand-red': '#e31e24',
        'brand-yellow': '#fdcb01',
        'tertiary-fixed-dim': '#c3c0ff',
        'on-tertiary-fixed': '#0f0069',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'on-primary-fixed': '#00164e',
        'inverse-surface': '#213145',
        'tertiary-container': '#2b15c6',
        'on-surface': '#0b1c30',
        outline: '#757682',
        'primary-fixed': '#dce1ff',
        'on-secondary-fixed-variant': '#004b73',
        'surface-container-low': '#eff4ff',
        'on-surface-variant': '#444651',
        'on-background': '#0b1c30',
        'on-tertiary-container': '#a5a2ff',
        'on-primary-container': '#90a8ff',
        tertiary: '#190093',
        'surface-tint': '#4059aa',
        'on-secondary-fixed': '#001d31',
        'on-primary-fixed-variant': '#264191',
        'tertiary-fixed': '#e2dfff',
        'surface-container-highest': '#d3e4fe',
        'inverse-primary': '#b6c4ff',
        'secondary-fixed-dim': '#93ccff',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#1e3a8a',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        secondary: '#006398',
        'secondary-container': '#5bb8fe',
        'outline-variant': '#c5c5d3',
        primary: '#264796', // azul del logo San Juan
        'surface-variant': '#d3e4fe',
        surface: '#f8f9ff',
        background: '#f8f9ff',
        'surface-container': '#e5eeff',
        'on-secondary-container': '#00476e',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'on-tertiary-fixed-variant': '#3323cc',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#b6c4ff',
        'secondary-fixed': '#cce5ff',
        'on-error': '#ffffff',
        'surface-container-high': '#dce9ff',
        'inverse-on-surface': '#eaf1ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'max-width': '1440px',
        unit: '4px',
        'margin-desktop': '32px',
        gutter: '24px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'label-md': ['Inter'],
        'body-lg': ['Inter'],
        'title-md': ['Inter'],
        'display-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'title-lg': ['Inter'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
